#!/bin/sh
#Generated with love at Sat Oct 6 07:33:15 2018 by JetBrains Toolbox 1.11.4269 (Aug 30 2018)

"/home/michael/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/182.4505.26/bin/pycharm.sh" "$@"

