#!/bin/sh
#Generated with love at Fri Jul 6 16:16:07 2018 by JetBrains Toolbox 1.9.3935 (Jun 20 2018)

"/home/michael/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/181.4445.76/bin/pycharm.sh" "$@"

